# docker-compose.yml
version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: docker-frontend
    volumes:
      - ./frontend:/frontend:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 